# Generated by Django 6.0.3 on 2026-03-31 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fazenda', models.CharField(max_length=100)),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_solo', models.CharField(choices=[('arenoso', 'Arenoso'), ('argiloso', 'Argiloso'), ('misto', 'Misto')], max_length=20)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriedade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
