# Generated by Django 6.0.3 on 2026-03-31 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('trator', 'Trator'), ('colheitadeira', 'Colheitadeira'), ('pulverizador', 'Pulverizador'), ('plantadeira', 'Plantadeira'), ('outro', 'Outro')], max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('identificacao', models.CharField(max_length=50)),
                ('horimetro', models.IntegerField(default=0)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.propriedade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
