# Generated by Django 6.0.3 on 2026-04-06 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_propriedade_usuario_tarefamaquina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='propriedade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='core.propriedade'),
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
                ('finalidade', models.CharField(max_length=50)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='core.propriedade')),
            ],
        ),
        migrations.CreateModel(
            name='Plantacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_planta', models.CharField(max_length=100)),
                ('tipo_planta', models.CharField(max_length=50)),
                ('area_plantada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_plantio', models.DateField()),
                ('previsao_colheita', models.DateField()),
                ('status', models.CharField(choices=[('plantado', 'Recém Plantado'), ('germinacao', 'Em Germinação'), ('desenvolvimento', 'Desenvolvimento Vegetativo'), ('colheita', 'Pronto para Colheita'), ('finalizado', 'Finalizado')], default='plantado', max_length=20)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantacoes', to='core.propriedade')),
            ],
        ),
    ]
