# Generated by Django 6.0.3 on 2026-04-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_maquina_propriedade_animal_plantacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='finalidade',
            new_name='identificacao',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='animal',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='animais/'),
        ),
        migrations.AddField(
            model_name='animal',
            name='nome_animal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Peso em kg', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='raca',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='sanitario',
            field=models.TextField(blank=True, help_text='Histórico de vacinas/medicamentos', null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('tratamento', 'Em Tratamento'), ('vendido', 'Vendido')], default='ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('bovino', 'Bovino'), ('suino', 'Suíno'), ('ovino', 'Ovino'), ('equino', 'Equino')], max_length=20),
        ),
    ]
