# Generated by Django 6.0.3 on 2026-04-15 14:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_finalidade_animal_identificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maquina',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantacao',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='propriedade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.propriedade'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sanitario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('tratamento', 'Tratamento'), ('vendido', 'Vendido')], default='ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='propriedade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.propriedade'),
        ),
        migrations.AlterField(
            model_name='plantacao',
            name='propriedade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.propriedade'),
        ),
        migrations.AlterField(
            model_name='plantacao',
            name='status',
            field=models.CharField(choices=[('plantado', 'Plantado'), ('germinacao', 'Germinação'), ('desenvolvimento', 'Desenvolvimento'), ('colheita', 'Colheita'), ('finalizado', 'Finalizado')], default='plantado', max_length=20),
        ),
    ]
