# Generated by Django 6.0.3 on 2026-04-15 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_animal_data_cadastro_maquina_data_cadastro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='plantacao',
            name='data_cadastro',
        ),
        migrations.AlterField(
            model_name='animal',
            name='peso',
            field=models.DecimalField(decimal_places=2, help_text='Peso em kg', max_digits=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='propriedade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='core.propriedade'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sanitario',
            field=models.TextField(blank=True, help_text='Histórico de vacinas/medicamentos', null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('tratamento', 'Em Tratamento'), ('vendido', 'Vendido')], default='ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='propriedade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='core.propriedade'),
        ),
        migrations.AlterField(
            model_name='plantacao',
            name='propriedade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantacoes', to='core.propriedade'),
        ),
        migrations.AlterField(
            model_name='plantacao',
            name='status',
            field=models.CharField(choices=[('plantado', 'Recém Plantado'), ('germinacao', 'Em Germinação'), ('desenvolvimento', 'Desenvolvimento Vegetativo'), ('colheita', 'Pronto para Colheita'), ('finalizado', 'Finalizado')], default='plantado', max_length=20),
        ),
    ]
