# Generated by Django 6.0.3 on 2026-04-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_animal_data_cadastro_maquina_data_cadastro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='plantacao',
            name='data_cadastro',
        ),
        migrations.AlterField(
            model_name='animal',
            name='peso',
            field=models.DecimalField(decimal_places=2, help_text='Peso em kg', max_digits=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sanitario',
            field=models.TextField(blank=True, help_text='Histórico de vacinas/medicamentos', null=True),
        ),
    ]
