# Generated by Django 6.0.3 on 2026-04-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_animal_data_criacao_maquina_data_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='sanitario',
        ),
    ]
